<?php
declare(strict_types=1);
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
$customer = $viewModels->require(Customer::class);
?>
<div class="md:w-1/2 w-full flex flex-wrap pr-4">
    <div class="w-full grid grid-cols-1 sm:grid-cols-2 gap-8 xl:col-span-2">
        <nav aria-label="Menu Tienda">
            <h2 class="text-md leading-5 font-semibold tracking-wider uppercase">Tienda</h2>
            <ul class="mt-4">
                <li><a href="<?= $escaper->escapeUrl($block->getUrl('quienes-somos')) ?>" class="text-base leading-6">Quiénes Somos</a></li>
                <li class="mt-4"><a href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>" class="text-base leading-6"><?= $escaper->escapeHtml(__('Mi Cuenta')) ?></a></li>
                <li class="mt-4"><a href="<?= $escaper->escapeUrl($block->getUrl('formas-de-comprar')) ?>" class="text-base leading-6">Formas de Compra</a></li>
                <li class="mt-4"><a href="<?= $escaper->escapeUrl($block->getUrl('envios')) ?>" class="text-base leading-6">Envíos</a></li>
                <li class="mt-4"><a href="<?= $escaper->escapeUrl($block->getUrl('experiencia-de-compra')) ?>" class="text-base leading-6">Experiencia de Compra</a></li>
                <li class="mt-4"><a href="<?= $escaper->escapeUrl($block->getUrl('contact')) ?>" class="text-base leading-6">Contacto</a></li>
                <li class="mt-4"><a href="<?= $escaper->escapeUrl($block->getUrl('blog')) ?>" class="text-base leading-6">Blog</a></li>
            </ul>
        </nav>
        <nav aria-label="Menu Legal">
            <h2 class="text-md leading-5 font-semibold tracking-wider uppercase">Legal</h2>
            <ul class="mt-4">
                <li><a href="<?= $escaper->escapeUrl($block->getUrl('aviso-de-privacidad')) ?>" class="text-base leading-6">Aviso de Privacidad</a></li>
                <li class="mt-4"><a href="<?= $escaper->escapeUrl($block->getUrl('referencias')) ?>" class="text-base leading-6">Referencias</a></li>
                <li class="mt-4"><a href="<?= $escaper->escapeUrl($block->getUrl('preguntas-o-sugerencias')) ?>" class="text-base leading-6">Preguntas o Sugerencias</a></li>
            </ul>
        </nav>
    </div>
</div>